-- CreateEnum
CREATE TYPE "SCHEDULED_REACTION_STATUS" AS ENUM ('PENDING', 'CANCELLED', 'FAILED', 'SUCCESS');

-- AlterTable
ALTER TABLE "ScheduledReaction" ADD COLUMN     "sendStatus" "SCHEDULED_REACTION_STATUS" NOT NULL DEFAULT 'PENDING';
